HSQuickLook.main.schema =
[
{
	"collection":"sgd1",
	"functionalObject":"/SGD1.CC1",
	"attributeSequence":"PRM",
	"period":"1",
	"blockName":"",
	"contents":{
		"WAIT_TIME1":{"type":"int","status":"ok","format":"%4X"},
		"WAIT_TIME2_1":{"type":"int","status":"ok","format":"%4X"},
		"WAIT_TIME2_2":{"type":"int","status":"ok","format":"%4X"},
		"WAIT_TIME3":{"type":"int","status":"ok","format":"%4X"},
		"WAIT_TIME4":{"type":"int","status":"ok","format":"%4X"},
		"CLK_SPEED1":{"type":"int","status":"ok","format":"%4X"},
		"CLK_SPEED2":{"type":"int","status":"ok","format":"%4X"},
		"PLS_RATE1":{"type":"int","status":"ok","format":"%4X"},
		"PLS_RATE2":{"type":"int","status":"ok","format":"%4X"},
		"PLS_RATE3":{"type":"int","status":"ok","format":"%4X"},
		"PLS_RATE4":{"type":"int","status":"ok","format":"%4X"},
		"PLS_RATE5":{"type":"int","status":"ok","format":"%4X"},
		"CLK_DLY1":{"type":"int","status":"ok","format":"%4X"},
		"CLK_DLY2":{"type":"int","status":"ok","format":"%4X"},
		"PTRG":{"type":"int","status":"ok","format":"%4X"},
		"CAL_PLS":{"type":"int","status":"ok","format":"%4X"},
		"CAL_PLS_TRG":{"type":"int","status":"ok","format":"%4X"},
		"TRG_MASK1":{"type":"int","status":"ok","format":"%4X"},
		"TRG_MASK2":{"type":"int","status":"ok","format":"%4X"},
		"TRG_MASK3":{"type":"int","status":"ok","format":"%4X"},
		"TRG_MASK4":{"type":"int","status":"ok","format":"%4X"},
		"WAIT_TIME5":{"type":"int","status":"ok","format":"%4X"},
		"WAIT_TIME6":{"type":"int","status":"ok","format":"%4X"},
		"FTRG_PLS_RATE3":{"type":"int","status":"ok","format":"%4X"},
		"CLK_DLY3":{"type":"int","status":"ok","format":"%4X"},
		"PLS_WD":{"type":"int","status":"ok","format":"%4X"},
		"FTRG":{"type":"int","status":"ok","format":"%4X"},
		"FBGO":{"type":"int","status":"ok","format":"%4X"},
		"FBGO_MASK":{"type":"int","status":"ok","format":"%4X"},
		"CHAIN_ENA":{"type":"int","status":"ok","format":"%8X"},
		"BUF_TYPE":{"type":"int","status":"ok","format":"%4X"},
		"EVNT_INVALID":{"type":"int","status":"ok","format":"%4X"}
	}
}
];
